### PR TITLE
Update the model for its dependencies

### LINKED ISSUE #10: Update the model for its dependencies
The syslog YANG model uses groupings/definitions from other models being developed in IETF. This issue will be used to update the syslog to include the newer version of those models. In particular, the models that it imports include:
- ietf-tls-client
- ietf-crypto-types
- ietf-tls-common
- ietf-truststore
- ietf-keystore
- iana-tls-ciper-suite-algs

### PR DESCRIPTION
**Pull request by mjethanandani**
Address issue #10

### CODE REVIEW

**Review by xorrkaz — APPROVED** [review]
Looks fine to me.  Are these baked enough that it makes sense to spin a new draft?

**Comment by kwatsen** [comment]
I'd wait until the dependent drafts exit IESG...
They're not technically stable until then.

**Comment by mjethanandani** [comment]
Are we expecting changes that might impact the syslog model?

**Comment by kwatsen** [comment]
Expecting? - no.
Can it happen? - yes.

Note that just a name-change may cause the tree-diagrams in this draft to need to be regenerated.

**Comment by mjethanandani** [comment]
Ok. Will not spin a draft, but will keep the changes.

**Pull request merged**
